#!/bin/bash
echo "Exploring Raspberry Pi Chapter 5 Performance Test Code"
echo "Building the Executables"
g++ -O3 n-body.cpp -o n-body
g++ -O3 --std=c++11  n-body2.cpp -o n-body2

echo "Building the Java Executable"
javac nbody.java

echo "Finished Building the Compiled Programs"
