######################################################################
# Automatically generated by qmake (3.0) Mon Nov 16 04:02:43 2015
######################################################################

TEMPLATE = app
QT += widgets
TARGET = simpleQt
INCLUDEPATH += .

# Input
SOURCES += simpleQt.cpp
